INSERT INTO quizzes (user_id,title,is_private) VALUES (1,'When an element is clicked, which phase occurs first, bubbling or capturing?',false);
INSERT INTO quizzes (user_id,title,is_private) VALUES (2,'What function can be used to stop an event from triggering all subsequent handlers?',false);
INSERT INTO quizzes (user_id,title,is_private) VALUES (1,'When you set an event, is it handle during the bubbling or capturing phase by default?',false);
INSERT INTO quizzes (user_id,title,is_private) VALUES (2,'How many continent are there in the world?',false);
INSERT INTO quizzes (user_id,title,is_private) VALUES (1,'How are you?',false);
INSERT INTO quizzes (user_id,title,is_private) VALUES (2,'Which record type maps a host name to an IP address? (IPv4)',true);
INSERT INTO quizzes (user_id,title,is_private) VALUES (1,'When performing DNS resolution, what is the sequence of name servers that are queried? (In order, first to last',false);
INSERT INTO quizzes (user_id,title,is_private) VALUES (2,'Which of the following best explains the difference between packages, modules, and libraries?',false);
INSERT INTO quizzes (user_id,title,is_private) VALUES (1,'Should the node_modules directory be committed to your project git repo?',false);
INSERT INTO quizzes (user_id,title,is_private) VALUES (2,,true);
INSERT INTO quizzes (user_id,title,is_private) VALUES (1,'Js',false);
