DROP TABLE IF EXISTS answers CASCADE;
CREATE TABLE answers (
id SERIAL PRIMARY KEY NOT NULL,
question_id INTEGER NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE,
answer TEXT NOT NULL,
is_right BOOLEAN NOT NULL
);
